# Prettier
arrowParens: 'always'
bracketSpacing: true
endOfLine: 'lf'
jsxSingleQuote: true
printWidth: 100
semi: false
singleQuote: true
tabWidth: 2

# PrettierX
spaceBeforeFunctionParen: true
generatorStarSpacing: true
yieldStarSpacing: true
alignTernaryLines: false
